"""Spec-to-test generator: turn the signatures in a spec's Low-Level Tasks into pytest contract tests.

Deterministic mode pins what the spec promises: each `def` exists in its module with the exact
parameter names and return annotation, and each `class` exists. Run it before the Director so
the loop has a test to close against. `--llm` adds behavioral tests written by Claude from the
objectives (review them: a generated test is a claim, not a proof).

Usage:
  uv run python -m specs.spec_to_tests examples/software/spec.md --out /tmp/test_contract.py
"""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

from pydantic import BaseModel, Field

from core.llm import Runner, get_runner
from core.types import AgentRequest, Spec

from .spec_validator import parse_spec

_FILE_RE = re.compile(r"(?:CREATE|UPDATE)\s+([\w/.-]+\.py)\b")
_DEF_RE = re.compile(r"\bdef\s+(\w+)\((.*?)\)\s*->\s*([^\n]*)")
_CLASS_RE = re.compile(r"\bclass\s+(\w+)")


class FunctionContract(BaseModel):
    module: str
    name: str
    params: list[str]
    returns: str


class Contracts(BaseModel):
    functions: list[FunctionContract] = Field(default_factory=list)
    classes: list[tuple[str, str]] = Field(default_factory=list)   # (module, class)


def _split_params(params: str) -> list[str]:
    """Split on top-level commas only (ignore commas inside brackets), keep parameter names."""
    names, depth, cur = [], 0, ""
    for ch in params + ",":
        if ch in "[(":
            depth += 1
        elif ch in "])":
            depth -= 1
        if ch == "," and depth == 0:
            name = re.split(r"[:=]", cur)[0].strip().lstrip("*")
            if name and name != "self":
                names.append(name)
            cur = ""
        else:
            cur += ch
    return names


def _return_type(rest: str) -> str:
    """Read a return annotation up to a top-level ':' or the first word that isn't part of a `|` union."""
    out, depth = "", 0
    for i, ch in enumerate(rest):
        if ch in "[(":
            depth += 1
        elif ch in "])":
            depth -= 1
        if depth == 0 and ch == ":":
            break
        if depth == 0 and ch == " " and not (rest[i:].lstrip().startswith("|") or out.rstrip().endswith("|")):
            break
        out += ch
    return out.strip()


def extract_contracts(spec: Spec) -> Contracts:
    out = Contracts()
    for task in spec.low_level_tasks:
        files = _FILE_RE.findall(task.prompt)
        if not files:
            continue
        module = Path(files[0]).stem
        for name, params, returns in _DEF_RE.findall(task.prompt):
            if not any(f.name == name and f.module == module for f in out.functions):
                out.functions.append(FunctionContract(module=module, name=name, params=_split_params(params),
                                                      returns=_return_type(returns)))
        for cls in _CLASS_RE.findall(task.prompt):
            if (module, cls) not in out.classes:
                out.classes.append((module, cls))
    return out


def render_tests(contracts: Contracts, source: str) -> str:
    modules = sorted({f.module for f in contracts.functions} | {m for m, _ in contracts.classes})
    lines = [
        f'"""Contract tests generated by specs/spec_to_tests.py from {source}. Regenerate; do not hand-edit."""',
        "",
        "import inspect",
        "import re",
        "",
        *[f"import {m}" for m in modules],
        "",
        "",
        "def _norm(annotation) -> str:",
        '    text = annotation if isinstance(annotation, str) else getattr(annotation, "__name__", str(annotation))',
        '    return re.sub(r"\\b\\w+\\.", "", text).replace(" ", "").replace("typing.", "")',
    ]
    for f in contracts.functions:
        lines += [
            "",
            "",
            f"def test_{f.module}_{f.name.lstrip('_')}_contract():",
            f'    fn = getattr({f.module}, "{f.name}", None)',
            f'    assert callable(fn), "{f.module}.{f.name} is missing"',
            "    sig = inspect.signature(fn)",
            f"    assert list(sig.parameters) == {f.params!r}",
            f"    assert _norm(sig.return_annotation) == _norm({f.returns!r})",
        ]
    for module, cls in contracts.classes:
        lines += ["", "", f"def test_{module}_{cls.lower()}_exists():",
                  f'    assert inspect.isclass(getattr({module}, "{cls}", None)), "{module}.{cls} is missing"']
    return "\n".join(lines) + "\n"


def llm_tests(spec_text: str, contracts: Contracts, runner: Runner, working_dir: Path) -> str | None:
    prompt = (
        "Write pytest behavioral tests for the spec below. Import only these modules: "
        f"{sorted({f.module for f in contracts.functions})}. Cover each Mid-Level Objective and the edge cases "
        "in the Implementation Notes. Reply with one ```python code block only.\n\n" + spec_text
    )
    resp = runner.run(AgentRequest(role="writer", prompt=prompt, model="sonnet", working_dir=str(working_dir)))
    m = re.search(r"```python\s*(.*?)```", resp.output, re.DOTALL)
    code = m.group(1) if m else ""
    try:
        ast.parse(code)
    except SyntaxError:
        return None
    return code if "def test_" in code else None


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate pytest contract tests from a spec.")
    ap.add_argument("spec", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--llm", action="store_true", help="also ask Claude for behavioral tests (<out>_behavior.py)")
    a = ap.parse_args(argv)
    text = a.spec.read_text()
    contracts = extract_contracts(parse_spec(text))
    if not contracts.functions and not contracts.classes:
        print(f"FAIL: no `def name(...) -> T` or `class Name` found in {a.spec} Low-Level Tasks")
        return 1
    a.out.write_text(render_tests(contracts, str(a.spec)))
    print(f"WROTE {a.out}: {len(contracts.functions)} function and {len(contracts.classes)} class contract(s)")
    if a.llm:
        code = llm_tests(text, contracts, get_runner(), a.spec.parent)
        if code is None:
            print("SKIPPED --llm: the reply had no valid test code")
            return 1
        behavior = a.out.with_name(f"{a.out.stem}_behavior.py")
        behavior.write_text(code)
        print(f"WROTE {behavior} (review before trusting it)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
